[general]
name=cat
pic=./assets/pic/cat.png
selection=./assets/pic/SelectedNPC.png
font=./cfg/sprites/spritesFont.ini
selectionOffsetX=0
selectionOffsetY=25
frames=12
delay=100

[small]
standStart=0
standEnd=3

leftStart=6
leftEnd=7

rightStart=4
rightEnd=5

downStart=8
downEnd=9

upStart=10
upEnd=11


[big]
pic=./assets/pic/Cat3.png
frames=6

;moods must be in order [Neutral] [Sad] [Angry] [Conserned] [Frowing] [Smiling]
neutral=./assets/sounds/click.wav
sad=./assets/sounds/pup.wav
angry=./assets/sounds/cork.wav
concerned=./assets/sounds/click.wav
frowning=./assets/sounds/woosh.wav
smiling=./assets/sounds/shortPipPip.wav

[initialInfo]
info="Just a usual beautiful small cat"

